name: CodeQualityAnalsis
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    CQA:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install -r 
              
            - name: Run Code quality lint tests for Dashboard App
              working-directory: ./CarPartWarehouseDashboard
              run: pnpm npx eslint

            - name: Run Code quality lint tests for Manager App
              working-directory: ./CarPartWarehouseManager
              run: pnpm npx eslint

    deploy:
      runs-on: ubuntu-latest
      needs:
        - CQA
      steps:
          - name: Check out the repo
            uses: actions/checkout@v4
          - name: Log in to Docker Hub
            uses: docker/login-action@v3.3.0
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Build and push Docker image Dashboard
            uses: docker/build-push-action@v6.9.0
            with:
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/carpartwarehousedashboard:latest
                context: ./CarPartWarehouseDashboard

          - name: Build and push Docker image Manager
            uses: docker/build-push-action@v6.9.0
            with:
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/carpartwarehousemanager:latest
                context: ./CarPartWarehouseManager


